remove unused and broken method
1: Symbol "Burglary" is neither a variable in the current scope nor a zero-ary function.
String: 1279412991::0.0: type checking failed for query
java.lang.IllegalStateException: Query has not yet been compiled.
  at blog.model.ArgSpecQuery.getVariable(ArgSpecQuery.java:82)
  at blog.BLOGUtil.getValue(BLOGUtil.java:117)
  ... 32 elided